### ISSUE TITLE
feat: No properties returned for TypeAlias

### ISSUE THREAD

**Issue by tswymer** [jordimarimon/ts-ast-parser#203]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/jordimarimon/ts-ast-parser/blob/main/CONTRIBUTING.md).
- [X] I have searched for [existing issues](https://github.com/jordimarimon/ts-ast-parser/issues) that already report this problem, without success.

### Version

Playground on the documentation website

### Current Behavior

When I pass an Interface to be serialized, I correctly receive a list of properties for that interface.
Doing the same thing with a TypeAlias I don't get a list of properties.

### Expected Behavior

I expect to receive a list of properties for a TypeAlias in the same way I receive them for an Interface

### Steps to Reproduce

Part the following example into the playground:

```
/**
 * This is the documentation
 * for MyFunctionProps.
 * 
 * @see https://www.typescriptlang.org/docs/handbook/jsx.html#attribute-type-checking
 * @param props My props param
 */
export type MyTypeProps = {
    /**
     * This is the documentation
     * for myTypeValue1.
     */
    myTypeValue1: string;
    /**
     * This is the documentation
     * for myTypeValue2.
     */
    myTypeValue2: number;
};

/**
 * This is the documentation
 * for MyInterfaceProps.
 */
export interface MyInterfaceProps {
    /**
     * This is the documentation
     * for myInterfaceValue1.
     */
    myInterfaceValue1: string;
    /**
     * This is the documentation
     * for myInterfaceValue2.
     */
    myInterfaceValue2: number;
}

```

which outputs this:

```
{
  "path": "unknown.ts",
  "imports": [],
  "declarations": [
    {
      "name": "MyTypeProps",
      "kind": "TypeAlias",
      "line": 8,
      "value": "{\n    /**\n     * This is the documentation\n     * for myTypeValue1.\n     */\n    myTypeValue1: string;\n    /**\n     * This is the documentation\n     * for myTypeValue2.\n     */\n    myTypeValue2: number;\n}",
      "jsDoc": [
        {
          "kind": "description",
          "value": "This is the documentation\nfor MyFunctionProps."
        },
        {
          "kind": "see",
          "value": "https://www.typescriptlang.org/docs/handbook/jsx.html#attribute-type-checking"
        },
        {
          "kind": "param",
          "value": {
            "name": "props",
            "description": "My props param"
          }
        }
      ]
    },
    {
      "name": "MyInterfaceProps",
      "kind": "Interface",
      "line": 25,
      "jsDoc": [
        {
          "kind": "description",
          "value": "This is the documentation\nfor MyInterfaceProps."
        }
      ],
      // This is what I want to see for the TypeAlias too
      "properties": [
        {
          "name": "myInterfaceValue1",
          "line": 30,
          "kind": "Property",
          "type": {
            "text": "string"
          },
          "jsDoc": [
            {
              "kind": "description",
              "value": "This is the documentation\nfor myInterfaceValue1."
            }
          ]
        },
        {
          "name": "myInterfaceValue2",
          "line": 35,
          "kind": "Property",
          "type": {
            "text": "number"
          },
          "jsDoc": [
            {
              "kind": "description",
              "value": "This is the documentation\nfor myInterfaceValue2."
            }
          ]
        }
      ]
    }
  ],
  "exports": [
    {
      "name": "MyTypeProps",
      "kind": "Named"
    },
    {
      "name": "MyInterfaceProps",
      "kind": "Named"
    }
  ]
}
```

**Comment by jordimarimon** [comment]
Hi!

Thanks for opening an issue.

You're right, I'm not reflecting any information for type aliases. I'm just reflecting the raw value, which is not quite useful.

As you already know, a type alias is a construct that can mean a variety of different things (the following are just a few examples of the different type aliases one can define):

```ts
type StringAlias = string;

type ArrayType = string[];

type UnionType = string | number;

type IntersectionType = string & number;

type ObjectLiteralType = {a: number};

type CombiningArrayWithLiteralTypeThroughUnion = ObjectLiteralType | ArrayType;

type ConditionalType<T> = T extends number ? 1 : 0;

// etc...
```

And one can combine them to create even more complex type aliases.

I'm in favor of making a more in depth analysis around type aliases. During the following week I will be trying to reflect more information for type aliases (at least the most basic ones like unions, intersections, array and object literals).

It's in my road map to support all the corner cases around type aliases but because this library is still in a very early stage I will be adding the support for type aliases in small steps.

For an initial phase (next week) I will support reflecting information about unions, intersections, array and object literal types. Also there will be support for combining any of the above mentioned. This should at least be enough for the majority of use cases.

In a near future I will be adding support for more complex cases.

For the next release (which I was planning to do today or tomorrow), probably it won't arrive the support for type aliases, but for the release I'm planning for one week from now, I'm pretty sure I can have something available that at least will solve your use case (object literal types).
