### ISSUE TITLE
feat: Skip Diagnostics

### ISSUE THREAD

**Issue by Buckwich** [jordimarimon/ts-ast-parser#204]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/jordimarimon/ts-ast-parser/blob/main/CONTRIBUTING.md).
- [X] I have searched for [existing issues](https://github.com/jordimarimon/ts-ast-parser/issues) that already report this problem, without success.

### Describe the Feature Request

It would be nice to add a flag/option to parseFromSource (and probably other functions) to skip diagnostics. In previous versions I was able to rewrite that function without the diagnostics check, but those exports were recently removed. My current workaround is to just remove the check in the js files. 

If you want I can also create a PR with a suggestion (depends on how you want to handle such parserOptions)

### Describe the Use Case

I only use a subset of the parser which does not require a full semantic diagnostic. I therefore would like to skip that step

**Comment by jordimarimon** [comment]
Hi!

Thanks for opening an issue. Sounds reasonable what you're asking.

I have added an option `skipDiagnostics` in all the `parseFrom*` functions to ignore semantic errors while analyzing the source files. By default, the option is disabled, so there is no breaking change.

In the following 2-3 days I will be releasing a new version with this new feature available.

An example of how to use the new option:

```ts
import { parseFromSource }  from '@ts-ast-parser/core';

// It won't stop the analysis if there are semantic errors in the code
const reflectedModule = await parseFromSource(`...`, {skipDiagnostics: true});
const serializedModule = reflectedModule?.serialize();
```

Be aware that there is a breaking change in the function `parseFromSource` in the next release. Now the funciton is async and returns a promise.

More information can be found in the [CHANGELOG.md](https://github.com/jordimarimon/ts-ast-parser/blob/main/packages/core/CHANGELOG.md).

The reason of this breaking change is because I needed the function to be async in browser environments because I have to load dynamically from the CDN all the TypeScript `lib.*.d.ts` files for the playground.

**Comment by Buckwich** [comment]
Thank you very much for that quick implementation. Looking forward to the release 🎉
